### ISSUE TITLE
error when running EXCL_TOTAL + syntax error

### ISSUE THREAD

**Issue by ktiedt** [nachoparker/btrfs-du#10]
`Subvolume                                                         Total  Exclusive  ID
─────────────────────────────────────────────────────────────────────────────────────────
@home                                                                               257
/usr/local/sbin/btrfs-du: line 118: EXCL_TOTAL +  : syntax error: operand expected (error token is "+  ")
─────────────────────────────────────────────────────────────────────────────────────────
Total exclusive data                                                             0Bytes`

**Comment by nachoparker** [comment]
Duplicate of #9
