### ISSUE TITLE
Will not work with nested subvolumes.

### ISSUE THREAD

**Issue by ktiedt** [nachoparker/btrfs-du#11]
BTRFS allows creating subvolumes inside of subvolumes for more granular control of things... however, btrfs-du, even if given the exact path of a nest subvolume will always return to the root subvolume.

Example

/home is a subvolume.

One of my user accounts has a service that we want highly regular backups via snapshots... so 

/home/user/service/live is a subvolume
/home/user/service/dev is a subvolume 

btrfs-du /home/user/service/live or btrfs-du . (from that working dir) always results in
@home/* snapshots being displayed

Just tried this locally because my display was messed up via SSH, and the output also is missing any values. (btrfsdu . ran from /home/user/live)

/home                                                                               257
/home/user/service/live                                                                285
/home/user/service/dev                                                               286

Is there any way to work around this?

**Comment by tkocher** [comment]
probably same issue for me, doing backup with btrfs-sxbackup and its difficult to estimate size of backups and script is doing nesting... Thanks for any hint!
