### ISSUE TITLE
Update `readme` with new output.

### ISSUE THREAD

**Issue by jpluimers** [nachoparker/btrfs-du#7]
Since the output changed, the readme needs to be updated.

Also mention support for legacy `btrfs`.

**Comment by nachoparker** [comment]
also put your name on it! ;P

or at least in the header comment

**Comment by jpluimers** [comment]
I didn't even think about that yet (too preoccupied <g>). Thanks!

**Comment by nachoparker** [comment]
Done

https://github.com/nachoparker/btrfs-du/commit/a3eab0a376ed1410b55f114ed62975725b538d19
